# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b4b20ead946f970057993bf9220dc7b6b8bcfbd23fc56ab5ec5994f36ea4157b361945c71ad2c58f27bce6290ac28f382daa3b7434766d68e553ae6dfcb14d

test:
  secret_key_base: 437dc36b2ad1b490f18c3d81b8671d4eb02a308077fd8cbc7c501ab4dc183157193cd4de44f954ea13c10a61ff3ff82ce631999be06f40c58769127de2637b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
